version: '3'
services:
  scraper:
    build: .
    # container_name: invest_dash
    command: ["cron", "-f"]
    volumes:
      - .:/app

  app:
    build: .
    # container_name: invest_dash
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8080 --reload
    ports: 
      - 8080:8080
    volumes: 
      - .:/app

volumes:
  .: